# -*- coding: utf-8 -*-
"""Deteksi_Rempah_App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icxpPFxkpyksk2CV6RYiPfHTzVUMctbk
"""

!pip install streamlit

import streamlit as st
import numpy as np
from PIL import Image
import tensorflow as tf
import os
import gdown

# URL Google Drive file model
MODEL_URL = "https://drive.google.com/uc?export=download&id=12bYRNfO6tryeCjidDFQREgSAR23LdYTf"
MODEL_PATH = "rempah_detection_model.h5"

# Fungsi untuk mengunduh model jika belum ada
def download_model():
    if not os.path.exists(MODEL_PATH):
        st.info("Mengunduh model dari Google Drive. Harap tunggu...")
        gdown.download(MODEL_URL, MODEL_PATH, quiet=False)

# Fungsi untuk memuat model
@st.cache_resource
def load_model():
    download_model()
    model = tf.keras.models.load_model(MODEL_PATH)
    return model

# Fungsi untuk memproses gambar
def preprocess_image(image, target_size=(224, 224)):
    image = image.resize(target_size)  # Ubah ukuran gambar ke 224x224 (sesuai dengan input model)
    image = np.array(image) / 255.0   # Normalisasi pixel (0-1)
    image = np.expand_dims(image, axis=0)  # Tambahkan batch dimension
    return image

# Fungsi untuk memproses gambar
def preprocess_image(image, target_size=(224, 224)):
    image = image.resize(target_size)
    image = np.array(image) / 255.0
    image = np.expand_dims(image, axis=0)
    return image

# Fungsi untuk prediksi
def predict_image(model, image):
    predictions = model.predict(image)
    class_idx = np.argmax(predictions)
    confidence = predictions[0][class_idx]
    return class_idx, confidence

# Daftar nama kelas (sesuaikan dengan dataset Anda)
class_names = [
              "Adas", "Andaliman", "Asam Jawa", "Bawang Bombai", "Bawang Merah", "Bawang Putih", "Biji Ketumbar", "Bukan Rempah", "Bunga Lawang",
              "Cengkeh", "Daun Jeruk", "Daun Kemangi", "Daun Ketumbar", "Daun Salam", "Jahe", "Jinten", "Kapulaga", "Kayu Manis", "Kayu Secang",
              "Kemiri", "Kemukus", "Kencur", "Kluwek", "Kunyit", "Lada", "Lengkuas", "Pala", "Saffron", "Serai", "Vanili", "Wijen"
              ]

# Mulai aplikasi Streamlit
st.title("Aplikasi Deteksi dan Prediksi Rempah Indonesia")
st.write("Unggah gambar rempah yang membuatmu bingung dan aplikasi akan memprediksi jenis rempah tersebut.")

# Upload gambar
uploaded_file = st.file_uploader("Pilih gambar rempah", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)  # Buka gambar dengan PIL
    st.image(image, caption="Gambar yang diunggah", use_column_width=True)  # Tampilkan gambar

    # Proses dan prediksi
    model = load_model()  # Muat model
    processed_image = preprocess_image(image)  # Proses gambar
    class_idx, confidence = predict_image(model, processed_image)  # Prediksi

    # Tampilkan hasil prediksi
    st.write(f"**Jenis Rempah:** {class_names[class_idx]}")
    st.write(f"**Kepercayaan Prediksi:** {confidence * 100:.2f}%")